[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="color" type="ru.itmo.web.hw4.model.User.Color" --]
[#-- @ftlvariable name="user_id" type="long" --]
[#-- @ftlvariable name="user" type="ru.itmo.web.hw4.model.User" --]
[#-- @ftlvariable name="users" type="ru.itmo.web.hw4.model.User[]" --]
[#-- @ftlvariable name="post_id" type="long" --]
[#-- @ftlvariable name="post" type="ru.itmo.web.hw4.model.Post" --]
[#-- @ftlvariable name="posts" type="ru.itmo.web.hw4.model.Post[]" --]
[#-- @ftlvariable name="handle" type="java.lang.String" --]
[#-- @ftlvariable name="current_url" type="java.lang.String" --]
